# Generated by Django 5.2.1 on 2025-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0006_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="team_img/%Y/%m/%d")),
                ("desc", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
